In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
from Job_Finder import find_job

In [2]:
df=pd.read_csv('Skill_Map.csv')
df.columns = ['job', 'skill']
df.head()

,job,skill
0,Vb.Net Developer,.NET Programming SQL SQL Server Microsoft C# A...
1,.NET Developer / Engineer,.NET Programming Microsoft C# SQL ASP JavaScri...
2,Academic / Guidance Counselor,Communication Skills Academic Advisement Writi...
3,Account Executive,Sales Communication Skills Building Effective ...
4,Account Manager / Representative,Communication Skills Sales Customer Service Bu...

In [3]:
len(df) ###  900 Jobs

900

In [4]:
s=input("Explain your skillset:\n")

Explain your skillset:
data science

In [5]:
l=input("Enter location?\n")

Enter location?
chennai

In [6]:
all_skills = df['skill'].values
all_jobs=df['job'].unique().tolist()

In [7]:
def find_related_jobs(s):
    doc = s
    skill_match_score = []
    dictionary_list = []
    for j in range(len(all_skills)):
        final_score = 0
        tfidf_vectorizer = TfidfVectorizer(ngram_range = (1,3))
        train_set = [doc , all_skills[j]]
        tfidf_train = tfidf_vectorizer.fit_transform(train_set)
        score = cosine_similarity(tfidf_train[0:1],tfidf_train)
        skill_match_score.append("%.2f" % score[0][1])
    dictionary = dict(zip(all_jobs, skill_match_score))
    dictionary_sorted_by_value = sorted(dictionary.items(), key=lambda kv: kv[1], reverse = True)
    for k in range(5):
        dictionary_list.append(dictionary_sorted_by_value[k])
    return (dictionary_list[0][0])

In [8]:
s=find_related_jobs(s)
t="z"
if s[-1]=='\xa0':
    s=s[:len(s)-1]
s

'Senior Data Scientist'

In [9]:
job_list=find_job(s,l)

https://www.indeed.co.in/rc/clk?jk=ad61008003f43da0&fccid=dd616958bd9ddc12&vjs=3
https://www.indeed.co.in/rc/clk?jk=25fc81bcd67b4ea2&fccid=0f4f2d112db7d324&vjs=3
https://www.indeed.co.in/rc/clk?jk=c1bdec2ca7416f84&fccid=1ae531c3cad5b133&vjs=3
https://www.indeed.co.in/rc/clk?jk=2c25f722fb2ed770&fccid=3799fa8ac2d1edf2&vjs=3
https://www.indeed.co.in/rc/clk?jk=33e4b46dfbf12501&fccid=82656d64a9a3e6a7&vjs=3
https://www.indeed.co.in/rc/clk?jk=6702479b65ea6d2e&fccid=5e118f74384e090a&vjs=3
https://www.indeed.co.in/rc/clk?jk=94bd82c47cefdb3d&fccid=cc4dc20349e35cc0&vjs=3
https://www.indeed.co.in/rc/clk?jk=69acb99ef8be9254&fccid=978d9fd9799d55a8&vjs=3
https://www.indeed.co.in/rc/clk?jk=083b83bf37532a84&fccid=49ff321cf42a70bd&vjs=3
https://www.indeed.co.in/rc/clk?jk=ffb53915da380bd0&fccid=83a42c889f63ae2e&vjs=3
https://www.freshersworld.com/jobs/data-scientist-jobs-in-chennai-core-hr-services-pvt-ltd-1012122
https://www.freshersworld.com/jobs/data-analyst-data-scientist-data-engineer-jobs-in-bangalore-pune-chennai-caia-center-for-ai-and-analytics-1019122
https://www.freshersworld.com/jobs/senior-engineer-jobs-in-chennai-standard-chartered-bank-1011097
https://www.freshersworld.com/jobs/data-entry-jobs-in-bangalore-mumbai-chennai-rms-solutions-inc-1010204
https://www.freshersworld.com/jobs/data-analyst-jobs-in-bangalore-chennai-hyderabad-iibm-institute-of-business-management-1001937
https://www.freshersworld.com/jobs/data-protection-jobs-in-chennai-core-hr-services-pvt-ltd-1013654
https://www.freshersworld.com/jobs/senior-telecaller-jobs-in-chennai-tlc-relationship-management-1018519
https://www.freshersworld.com/jobs/data-entry-jobs-in-chennai-jvkds-enterprices-1017886
https://www.freshersworld.com/jobs/senior-engineer-design-jobs-in-chennai-caterpillar-1010026
https://www.freshersworld.com/jobs/senior-para-planner-jobs-in-chennai-talent-corner-hr-services-private-limited-1004894
https://www.freshersworld.com/jobs/senior-sales-associate-jobs-in-chennai-for-a-client-of-teamlease-services-ltd-1001671
https://www.freshersworld.com/jobs/senior-costing-officer-jobs-in-chennai-prernaa-consulting-services-1003875
https://www.freshersworld.com/jobs/senior-ui-developer-jobs-in-gurgaon-bangalore-mumbai-ibm-1003722
https://www.freshersworld.com/jobs/senior-telesales-executive-jobs-in-chennai-primitive-healthcare-1009753
https://www.freshersworld.com/jobs/senior-test-professional-jobs-in-chennai-siemens-technology-and-services-private-limited-1003545
https://www.freshersworld.com/jobs/online-data-entry-jobs-in-bangalore-chennai-noida-web-solutions-1001815
https://www.freshersworld.com/jobs/data-entry-operator-jobs-in-chennai-meegen-solutions-1019381
https://www.freshersworld.com/jobs/online-data-entry-jobs-in-chennai-coimbatore-madurai-modinity-technologies-1012644
https://www.freshersworld.com/jobs/data-and-analytics-jobs-in-chennai-desicrew-solutions-1010020
https://www.freshersworld.com/jobs/c11-big-data-jobs-in-chennai-for-a-client-of-teamlease-services-ltd-986929
https://www.freshersworld.com/jobs/data-entry-operator-jobs-in-chennai-fresherslive-1017001
https://www.freshersworld.com/jobs/data-entry-typist-jobs-in-chennai-coimbatore-madurai-jk-infosoft-ltd-1016438
https://www.freshersworld.com/jobs/clerical-data-entry-jobs-in-bangalore-chennai-rms-solutions-inc-986064
https://www.freshersworld.com/jobs/data-entry-executive-jobs-in-bangalore-chennai-hyderabad-eminentminds-1011224
https://www.freshersworld.com/jobs/data-science-engineers-jobs-in-pune-chennai-hyderabad-iibm-institute-of-business-management-997494
https://www.freshersworld.com/jobs/online-data-entry-jobs-in-chennai-legality-simplified-llp-996750
https://www.freshersworld.com/jobs/senior-graphic-designer-jobs-in-chennai-crazy-pencilz-1016625
https://www.freshersworld.com/jobs/senior-trainee-engineer-jobs-in-bangalore-chennai-hyderabad-n-k-saha-1009494
https://www.freshersworld.com/jobs/senior-graphic-designer-jobs-in-chennai-the-mad-innovations-1009264
https://www.freshersworld.com/jobs/senior-sales-executive-jobs-in-chennai-brancs-india-tools-pvt-ltd-chennai-992088
https://www.freshersworld.com/jobs/senior-java-developer-jobs-in-bangalore-chennai-atos-syntel-985749
https://www.freshersworld.com/jobs/senior-software-developer-jobs-in-chennai-industrial-soft-solutions-systems-981238
https://www.freshersworld.com/jobs/data-entry-operator-jobs-in-bangalore-chennai-coimbatore-mgm-infotech-1005683
https://www.freshersworld.com/jobs/administrative-assistant-data-entry-clerk-data-processing-executive-jobs-in-chennai-fly-care-india-1017037
https://www.freshersworld.com/jobs/senior-trainee-civil-engineer-jobs-in-bangalore-chennai-hyderabad-n-k-saha-1010555
https://www.freshersworld.com/jobs/senior-executive-voice-process-jobs-in-chennai-worksfreak-1010233
https://www.freshersworld.com/jobs/senior-qa-engineer-remote-jobs-in-chennai-crossover-for-work-1016946
https://www.freshersworld.com/jobs/sms-sending-data-entry-jobs-in-chennai-noida-hyderabad-jk-infosoft-ltd-1017473
https://www.freshersworld.com/jobs/database-administrator-data-engineer-jobs-in-chennai-core-hr-services-pvt-ltd-1013672
https://www.freshersworld.com/jobs/process-data-engineer-ssw-jobs-in-chennai-shell-1012054
https://www.freshersworld.com/jobs/data-science-internship-online-jobs-in-bangalore-chennai-hyderabad-iibm-institute-of-business-management-1005366
https://www.freshersworld.com/jobs/data-entry-back-office-jobs-in-vijayawada-bangalore-chennai-freelancer-amit-991506
https://www.freshersworld.com/jobs/senior-officer-finance-dept-jobs-in-chennai-for-a-client-of-teamlease-services-ltd-1003274
https://www.freshersworld.com/jobs/ui-ux-developer-senior-developer-jobs-in-chennai-falaina-1004844
https://www.freshersworld.com/jobs/big-data-platform-product-manager-jobs-in-chennai-mbe-holdings-limited-1012065
https://www.freshersworld.com/jobs/cloud-data-engineer-graduate-trainee-jobs-in-chennai-agilisium-consulting-1013641
https://www.freshersworld.com/jobs/professor-senior-consultant-consultant-neurology-jobs-in-chennai-sri-ramachandra-university-1005750
https://www.freshersworld.com/jobs/senior-webcenter-content-webcenter-portal-specialist-jobs-in-chennai-netsuite-inc-1009978
https://www.freshersworld.com/jobs/project-data-entry-operator-grade-a-jobs-in-chennai-national-institute-of-epidemiology-1010130
https://www.freshersworld.com/jobs/project-data-entry-operator-grade-a-jobs-in-chennai-national-institute-of-epidemiology-1010126
https://www.timesjobs.com/job-detail/senior-data-scientist-remote-work-from-home-wallethub-bengaluru-bangalore-chennai-delhi-ncr-hyderabad-secunderabad-mumbai-10-to-15-yrs-jobid-PEEYIlMFxu5zpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-data-scientist-canvas27-com-ahmedabad-bengaluru-bangalore-chennai-delhi-delhi-ncr-1-to-6-yrs-jobid-IKcVfAAq1IdzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-data-scientist-thedatateam-chennai-bengaluru-bangalore-10-to-13-yrs-jobid-dYupGy00r6ZzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-data-scientist-analytics-vidhya-chennai-7-to-10-yrs-jobid-pK4FdGSltnNzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-data-scientist-machine-learning-hr-jobs-placements-ahmedabad-bengaluru-bangalore-chennai-delhi-gurgaon-5-to-10-yrs-jobid-GuPVWXTeeeNzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-data-scientist-aws-professional-services-amazon-india-pvt-ltd-hyderabad-secunderabad-mumbai-delhi-chennai-pune-12-to-15-yrs-jobid-yVOLIfYhdTZzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-data-scientist-aws-professional-services-amazon-india-pvt-ltd-hyderabad-secunderabad-chennai-delhi-ncr-pune-bengaluru-bangalore-12-to-15-yrs-jobid-9cw1Qd14l6ZzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/data-analyst-s-m-placement-ahmedabad-bengaluru-bangalore-chennai-kolkata-mumbai-2-to-7-yrs-jobid-oNj74dDu__SLASH__q5zpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-marketing-communications-manager-tesco-supermarket-bengaluru-bangalore-chennai-hyderabad-secunderabad-kolkata-mumbai-4-to-9-yrs-jobid-kVqMjZiIPXJzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-accoutant-accoutant-construction-company-bengaluru-bangalore-chennai-hyderabad-secunderabad-kolkata-8-to-13-yrs-jobid-GcHu3OS72__PLUS__1zpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-executive-da-larete-consultants-chennai-4-to-6-yrs-jobid-kgJkIqFrw19zpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/data-science-internship-iibm-institute-of-business-management-ahmedabad-bengaluru-bangalore-chennai-hyderabad-secunderabad-mumbai-0-to-3-yrs-jobid-lDrpq4uIrqpzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-automation-qa-engineer-remote-wallethub-bengaluru-bangalore-chennai-delhi-ncr-hyderabad-secunderabad-mumbai-5-to-10-yrs-jobid-YMUuRxrLYsFzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/required-data-entry-executive-earn-upto-40k-p-m-call-hr-risika-softech-solutions-ahmedabad-bengaluru-bangalore-chennai-delhi-delhi-ncr-0-to-3-yrs-jobid-LCi9fLcN__SLASH__4hzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/warehouse-manager-green-farm-kota-udaipur-chennai-coimbatore-cuddalore-4-to-9-yrs-jobid-e7Q9EqsvvLpzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/business-analyst-www-iibmindia-in-bengaluru-bangalore-chennai-gurgaon-hyderabad-secunderabad-mumbai-0-to-3-yrs-jobid-226OyssLzAhzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/senior-quality-assurance-engineer-manual-testing-remote-wallethub-bengaluru-bangalore-chennai-delhi-ncr-hyderabad-secunderabad-mumbai-5-to-10-yrs-jobid-HOVyjQjsg9lzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/industrial-mechanic-agricultural-company-ahmedabad-chennai-hyderabad-secunderabad-mumbai-7-to-12-yrs-jobid-7WwEJP04nxRzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/marketing-manager-tesco-stores-ltd-ahmedabad-bengaluru-bangalore-chennai-kolkata-mumbai-2-to-7-yrs-jobid-WDStcRdEqABzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/executive-administrative-assistant-tesco-supermarket-ahmedabad-chennai-hyderabad-secunderabad-kolkata-mumbai-2-to-7-yrs-jobid-aBNZyh0bbNpzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/civil-engineer-tesco-plc-ahmedabad-chennai-hyderabad-secunderabad-kolkata-mumbai-2-to-7-yrs-jobid-vaXGuKbC5INzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/technician-s-m-placement-chennai-kolkata-mumbai-pune-thiruvananthapuram-1-to-6-yrs-jobid-H0YtL5zJN3BzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/b2b-sales-executive-supermarket-chennai-hyderabad-secunderabad-kolkata-mumbai-thrissur-2-to-7-yrs-jobid-as7SzcURJ__PLUS__ZzpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/pathologist-pathology-job-museum-chennai-1-to-3-yrs-jobid-g4OcLpYRng1zpSvf__PLUS__uAgZw==&source=srp
https://www.timesjobs.com/job-detail/admin-assistant-assistant-manager-b2b-sales-marketing-s-m-placement-ahmedabad-chennai-kolkata-mumbai-pune-3-to-8-yrs-jobid-__SLASH__tpU4E7DcudzpSvf__PLUS__uAgZw==&source=srp

                                            Job Title  \
0                               SENIOR DATA SCIENTIST
1                               Senior Data Scientist
2                               Senior Data Scientist
3                               Data Scientist Senior
4                               Senior Data Scientist
..                                                ...
20                                     Civil Engineer
21                                         Technician
22                              "B2B Sales Executive"
23                            pathologist , pathology
24  Admin Assistant , "Assistant Manager - B2B Sal...

                            Company  \
0                     The Data Team
1                          Poshmark
2                      Intellithink
3   ANI Calls India Private Limited
4                          Ericsson
..                              ...
20           S M Placement\r\n
21           S M Placement\r\n
22           S M Placement\r\n
23              Job Museum\r\n
24           S M Placement\r\n

                                                 Link  \
0   https://www.indeed.co.in/rc/clk?jk=ad61008003f...
1   https://www.indeed.co.in/rc/clk?jk=25fc81bcd67...
2   https://www.indeed.co.in/rc/clk?jk=c1bdec2ca74...
3   https://www.indeed.co.in/rc/clk?jk=2c25f722fb2...
4   https://www.indeed.co.in/rc/clk?jk=33e4b46dfbf...
..                                                ...
20  https://www.timesjobs.com/job-detail/civil-eng...
21  https://www.timesjobs.com/job-detail/technicia...
22  https://www.timesjobs.com/job-detail/b2b-sales...
23  https://www.timesjobs.com/job-detail/pathologi...
24  https://www.timesjobs.com/job-detail/admin-ass...

                                      Job_Description Location  \
0   Location: Chennai / Bangalore\n\nThe Data Team...  chennai
1   Are you a Data Scientist who is passionate abo...  chennai
2   Extensive experience working with large comple...  chennai
3   Job Description :\nâ€¢ Work comfortably with\n...  chennai
4   Date: Aug 28, 2020\n\nAs the tech firm that cr...  chennai
..                                                ...      ...
20  \n\nJob Description\nMarketing Coordinator Job...  chennai
21  \n\nJob Description\nMarketing Coordinator Job...  chennai
22  \n\nJob Description\nMarketing Coordinator Job...  chennai
23  \n\nJob Description\nWe are seeking an experie...  chennai
24  \n\nJob Description\nThe successful candidate ...  chennai

                                              Job_Rec
0                               Senior Data Scientist
1                               Senior Data Scientist
2                               Senior Data Scientist
3                               Senior Data Scientist
4                               Senior Data Scientist
..                                                ...
20  Admin Assistant , "Assistant Manager - B2B Sal...
21  Admin Assistant , "Assistant Manager - B2B Sal...
22  Admin Assistant , "Assistant Manager - B2B Sal...
23  Admin Assistant , "Assistant Manager - B2B Sal...
24  Admin Assistant , "Assistant Manager - B2B Sal...

[85 rows x 6 columns]

In [10]:
job_list

,Job Title,Company,Link,Job_Description,Location,Job_Rec
0,SENIOR DATA SCIENTIST,The Data Team,https://www.indeed.co.in/rc/clk?jk=ad61008003f...,Location: Chennai / Bangalore\n\nThe Data Team...,chennai,Senior Data Scientist
1,Senior Data Scientist,Poshmark,https://www.indeed.co.in/rc/clk?jk=25fc81bcd67...,Are you a Data Scientist who is passionate abo...,chennai,Senior Data Scientist
2,Senior Data Scientist,Intellithink,https://www.indeed.co.in/rc/clk?jk=c1bdec2ca74...,Extensive experience working with large comple...,chennai,Senior Data Scientist
3,Data Scientist Senior,ANI Calls India Private Limited,https://www.indeed.co.in/rc/clk?jk=2c25f722fb2...,Job Description :\nâ€¢ Work comfortably with\n...,chennai,Senior Data Scientist
4,Senior Data Scientist,Ericsson,https://www.indeed.co.in/rc/clk?jk=33e4b46dfbf...,"Date: Aug 28, 2020\n\nAs the tech firm that cr...",chennai,Senior Data Scientist
...,...,...,...,...,...,...
20,Civil Engineer,S M Placement\r\n,https://www.timesjobs.com/job-detail/civil-eng...,\n\nJob Description\nMarketing Coordinator Job...,chennai,"Admin Assistant , ""Assistant Manager - B2B Sal..."
21,Technician,S M Placement\r\n,https://www.timesjobs.com/job-detail/technicia...,\n\nJob Description\nMarketing Coordinator Job...,chennai,"Admin Assistant , ""Assistant Manager - B2B Sal..."
22,"""B2B Sales Executive""",S M Placement\r\n,https://www.timesjobs.com/job-detail/b2b-sales...,\n\nJob Description\nMarketing Coordinator Job...,chennai,"Admin Assistant , ""Assistant Manager - B2B Sal..."
23,"pathologist , pathology",Job Museum\r\n,https://www.timesjobs.com/job-detail/pathologi...,\n\nJob Description\nWe are seeking an experie...,chennai,"Admin Assistant , ""Assistant Manager - B2B Sal..."
24,"Admin Assistant , ""Assistant Manager - B2B Sal...",S M Placement\r\n,https://www.timesjobs.com/job-detail/admin-ass...,\n\nJob Description\nThe successful candidate ...,chennai,"Admin Assistant , ""Assistant Manager - B2B Sal..."